"use strict";
var __esDecorate = (this && this.__esDecorate) || function (ctor, descriptorIn, decorators, contextIn, initializers, extraInitializers) {
    function accept(f) { if (f !== void 0 && typeof f !== "function") throw new TypeError("Function expected"); return f; }
    var kind = contextIn.kind, key = kind === "getter" ? "get" : kind === "setter" ? "set" : "value";
    var target = !descriptorIn && ctor ? contextIn["static"] ? ctor : ctor.prototype : null;
    var descriptor = descriptorIn || (target ? Object.getOwnPropertyDescriptor(target, contextIn.name) : {});
    var _, done = false;
    for (var i = decorators.length - 1; i >= 0; i--) {
        var context = {};
        for (var p in contextIn) context[p] = p === "access" ? {} : contextIn[p];
        for (var p in contextIn.access) context.access[p] = contextIn.access[p];
        context.addInitializer = function (f) { if (done) throw new TypeError("Cannot add initializers after decoration has completed"); extraInitializers.push(accept(f || null)); };
        var result = (0, decorators[i])(kind === "accessor" ? { get: descriptor.get, set: descriptor.set } : descriptor[key], context);
        if (kind === "accessor") {
            if (result === void 0) continue;
            if (result === null || typeof result !== "object") throw new TypeError("Object expected");
            if (_ = accept(result.get)) descriptor.get = _;
            if (_ = accept(result.set)) descriptor.set = _;
            if (_ = accept(result.init)) initializers.unshift(_);
        }
        else if (_ = accept(result)) {
            if (kind === "field") initializers.unshift(_);
            else descriptor[key] = _;
        }
    }
    if (target) Object.defineProperty(target, contextIn.name, descriptor);
    done = true;
};
var __runInitializers = (this && this.__runInitializers) || function (thisArg, initializers, value) {
    var useValue = arguments.length > 2;
    for (var i = 0; i < initializers.length; i++) {
        value = useValue ? initializers[i].call(thisArg, value) : initializers[i].call(thisArg);
    }
    return useValue ? value : void 0;
};
var __setFunctionName = (this && this.__setFunctionName) || function (f, name, prefix) {
    if (typeof name === "symbol") name = name.description ? "[".concat(name.description, "]") : "";
    return Object.defineProperty(f, "name", { configurable: true, value: prefix ? "".concat(prefix, " ", name) : name });
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.Property = void 0;
var typeorm_1 = require("typeorm");
var category_entity_1 = require("./category.entity");
var community_entity_1 = require("./community.entity");
var Property = function () {
    var _classDecorators = [(0, typeorm_1.Entity)('mw_place_an_ad')];
    var _classDescriptor;
    var _classExtraInitializers = [];
    var _classThis;
    var _id_decorators;
    var _id_initializers = [];
    var _id_extraInitializers = [];
    var _title_decorators;
    var _title_initializers = [];
    var _title_extraInitializers = [];
    var _slug_decorators;
    var _slug_initializers = [];
    var _slug_extraInitializers = [];
    var _description_decorators;
    var _description_initializers = [];
    var _description_extraInitializers = [];
    var _short_description_decorators;
    var _short_description_initializers = [];
    var _short_description_extraInitializers = [];
    var _price_decorators;
    var _price_initializers = [];
    var _price_extraInitializers = [];
    var _purpose_decorators;
    var _purpose_initializers = [];
    var _purpose_extraInitializers = [];
    var _bedrooms_decorators;
    var _bedrooms_initializers = [];
    var _bedrooms_extraInitializers = [];
    var _bathrooms_decorators;
    var _bathrooms_initializers = [];
    var _bathrooms_extraInitializers = [];
    var _category_id_decorators;
    var _category_id_initializers = [];
    var _category_id_extraInitializers = [];
    var _subcategory_id_decorators;
    var _subcategory_id_initializers = [];
    var _subcategory_id_extraInitializers = [];
    var _country_decorators;
    var _country_initializers = [];
    var _country_extraInitializers = [];
    var _state_decorators;
    var _state_initializers = [];
    var _state_extraInitializers = [];
    var _city_decorators;
    var _city_initializers = [];
    var _city_extraInitializers = [];
    var _district_decorators;
    var _district_initializers = [];
    var _district_extraInitializers = [];
    var _latitude_decorators;
    var _latitude_initializers = [];
    var _latitude_extraInitializers = [];
    var _longitude_decorators;
    var _longitude_initializers = [];
    var _longitude_extraInitializers = [];
    var _phone_decorators;
    var _phone_initializers = [];
    var _phone_extraInitializers = [];
    var _user_id_decorators;
    var _user_id_initializers = [];
    var _user_id_extraInitializers = [];
    var _status_decorators;
    var _status_initializers = [];
    var _status_extraInitializers = [];
    var _is_trash_decorators;
    var _is_trash_initializers = [];
    var _is_trash_extraInitializers = [];
    var _priority_decorators;
    var _priority_initializers = [];
    var _priority_extraInitializers = [];
    var _created_at_decorators;
    var _created_at_initializers = [];
    var _created_at_extraInitializers = [];
    var _updated_at_decorators;
    var _updated_at_initializers = [];
    var _updated_at_extraInitializers = [];
    var _category_decorators;
    var _category_initializers = [];
    var _category_extraInitializers = [];
    var _community_decorators;
    var _community_initializers = [];
    var _community_extraInitializers = [];
    var Property = _classThis = /** @class */ (function () {
        function Property_1() {
            this.id = __runInitializers(this, _id_initializers, void 0);
            this.title = (__runInitializers(this, _id_extraInitializers), __runInitializers(this, _title_initializers, void 0));
            this.slug = (__runInitializers(this, _title_extraInitializers), __runInitializers(this, _slug_initializers, void 0));
            this.description = (__runInitializers(this, _slug_extraInitializers), __runInitializers(this, _description_initializers, void 0));
            this.short_description = (__runInitializers(this, _description_extraInitializers), __runInitializers(this, _short_description_initializers, void 0));
            this.price = (__runInitializers(this, _short_description_extraInitializers), __runInitializers(this, _price_initializers, void 0));
            this.purpose = (__runInitializers(this, _price_extraInitializers), __runInitializers(this, _purpose_initializers, void 0)); // sale, rent
            this.bedrooms = (__runInitializers(this, _purpose_extraInitializers), __runInitializers(this, _bedrooms_initializers, void 0));
            this.bathrooms = (__runInitializers(this, _bedrooms_extraInitializers), __runInitializers(this, _bathrooms_initializers, void 0));
            this.category_id = (__runInitializers(this, _bathrooms_extraInitializers), __runInitializers(this, _category_id_initializers, void 0));
            this.subcategory_id = (__runInitializers(this, _category_id_extraInitializers), __runInitializers(this, _subcategory_id_initializers, void 0));
            this.country = (__runInitializers(this, _subcategory_id_extraInitializers), __runInitializers(this, _country_initializers, void 0));
            this.state = (__runInitializers(this, _country_extraInitializers), __runInitializers(this, _state_initializers, void 0));
            this.city = (__runInitializers(this, _state_extraInitializers), __runInitializers(this, _city_initializers, void 0));
            this.district = (__runInitializers(this, _city_extraInitializers), __runInitializers(this, _district_initializers, void 0));
            this.latitude = (__runInitializers(this, _district_extraInitializers), __runInitializers(this, _latitude_initializers, void 0));
            this.longitude = (__runInitializers(this, _latitude_extraInitializers), __runInitializers(this, _longitude_initializers, void 0));
            this.phone = (__runInitializers(this, _longitude_extraInitializers), __runInitializers(this, _phone_initializers, void 0));
            this.user_id = (__runInitializers(this, _phone_extraInitializers), __runInitializers(this, _user_id_initializers, void 0));
            this.status = (__runInitializers(this, _user_id_extraInitializers), __runInitializers(this, _status_initializers, void 0));
            this.is_trash = (__runInitializers(this, _status_extraInitializers), __runInitializers(this, _is_trash_initializers, void 0));
            this.priority = (__runInitializers(this, _is_trash_extraInitializers), __runInitializers(this, _priority_initializers, void 0));
            this.created_at = (__runInitializers(this, _priority_extraInitializers), __runInitializers(this, _created_at_initializers, void 0));
            this.updated_at = (__runInitializers(this, _created_at_extraInitializers), __runInitializers(this, _updated_at_initializers, void 0));
            // Relations
            this.category = (__runInitializers(this, _updated_at_extraInitializers), __runInitializers(this, _category_initializers, void 0));
            this.community = (__runInitializers(this, _category_extraInitializers), __runInitializers(this, _community_initializers, void 0));
            __runInitializers(this, _community_extraInitializers);
        }
        return Property_1;
    }());
    __setFunctionName(_classThis, "Property");
    (function () {
        var _metadata = typeof Symbol === "function" && Symbol.metadata ? Object.create(null) : void 0;
        _id_decorators = [(0, typeorm_1.PrimaryGeneratedColumn)()];
        _title_decorators = [(0, typeorm_1.Column)({ name: 'ad_title', length: 250 })];
        _slug_decorators = [(0, typeorm_1.Column)({ length: 250, nullable: true })];
        _description_decorators = [(0, typeorm_1.Column)({ name: 'ad_description', type: 'text', nullable: true })];
        _short_description_decorators = [(0, typeorm_1.Column)({ name: 'ad_short_description', type: 'text', nullable: true })];
        _price_decorators = [(0, typeorm_1.Column)({ type: 'decimal', precision: 14, scale: 2 })];
        _purpose_decorators = [(0, typeorm_1.Column)({ name: 'listing_type', length: 1, nullable: true })];
        _bedrooms_decorators = [(0, typeorm_1.Column)({ nullable: true })];
        _bathrooms_decorators = [(0, typeorm_1.Column)({ nullable: true })];
        _category_id_decorators = [(0, typeorm_1.Column)({ nullable: true })];
        _subcategory_id_decorators = [(0, typeorm_1.Column)({ name: 'sub_category_id', nullable: true })];
        _country_decorators = [(0, typeorm_1.Column)({ nullable: true })];
        _state_decorators = [(0, typeorm_1.Column)({ nullable: true })];
        _city_decorators = [(0, typeorm_1.Column)({ nullable: true })];
        _district_decorators = [(0, typeorm_1.Column)({ nullable: true })];
        _latitude_decorators = [(0, typeorm_1.Column)({ name: 'location_latitude', length: 150, nullable: true })];
        _longitude_decorators = [(0, typeorm_1.Column)({ name: 'location_longitude', length: 150, nullable: true })];
        _phone_decorators = [(0, typeorm_1.Column)({ name: 'mobile_number', length: 15, nullable: true })];
        _user_id_decorators = [(0, typeorm_1.Column)({ nullable: true })];
        _status_decorators = [(0, typeorm_1.Column)({ type: 'enum', enum: ['A', 'I'], default: 'A' })];
        _is_trash_decorators = [(0, typeorm_1.Column)({ name: 'isTrash', type: 'enum', enum: ['0', '1'], default: '0' })];
        _priority_decorators = [(0, typeorm_1.Column)({ default: 0 })];
        _created_at_decorators = [(0, typeorm_1.Column)({ name: 'date_added', type: 'datetime' })];
        _updated_at_decorators = [(0, typeorm_1.Column)({ name: 'last_updated', type: 'timestamp' })];
        _category_decorators = [(0, typeorm_1.ManyToOne)(function () { return category_entity_1.Category; }), (0, typeorm_1.JoinColumn)({ name: 'category_id' })];
        _community_decorators = [(0, typeorm_1.ManyToOne)(function () { return community_entity_1.Community; }), (0, typeorm_1.JoinColumn)({ name: 'city' })];
        __esDecorate(null, null, _id_decorators, { kind: "field", name: "id", static: false, private: false, access: { has: function (obj) { return "id" in obj; }, get: function (obj) { return obj.id; }, set: function (obj, value) { obj.id = value; } }, metadata: _metadata }, _id_initializers, _id_extraInitializers);
        __esDecorate(null, null, _title_decorators, { kind: "field", name: "title", static: false, private: false, access: { has: function (obj) { return "title" in obj; }, get: function (obj) { return obj.title; }, set: function (obj, value) { obj.title = value; } }, metadata: _metadata }, _title_initializers, _title_extraInitializers);
        __esDecorate(null, null, _slug_decorators, { kind: "field", name: "slug", static: false, private: false, access: { has: function (obj) { return "slug" in obj; }, get: function (obj) { return obj.slug; }, set: function (obj, value) { obj.slug = value; } }, metadata: _metadata }, _slug_initializers, _slug_extraInitializers);
        __esDecorate(null, null, _description_decorators, { kind: "field", name: "description", static: false, private: false, access: { has: function (obj) { return "description" in obj; }, get: function (obj) { return obj.description; }, set: function (obj, value) { obj.description = value; } }, metadata: _metadata }, _description_initializers, _description_extraInitializers);
        __esDecorate(null, null, _short_description_decorators, { kind: "field", name: "short_description", static: false, private: false, access: { has: function (obj) { return "short_description" in obj; }, get: function (obj) { return obj.short_description; }, set: function (obj, value) { obj.short_description = value; } }, metadata: _metadata }, _short_description_initializers, _short_description_extraInitializers);
        __esDecorate(null, null, _price_decorators, { kind: "field", name: "price", static: false, private: false, access: { has: function (obj) { return "price" in obj; }, get: function (obj) { return obj.price; }, set: function (obj, value) { obj.price = value; } }, metadata: _metadata }, _price_initializers, _price_extraInitializers);
        __esDecorate(null, null, _purpose_decorators, { kind: "field", name: "purpose", static: false, private: false, access: { has: function (obj) { return "purpose" in obj; }, get: function (obj) { return obj.purpose; }, set: function (obj, value) { obj.purpose = value; } }, metadata: _metadata }, _purpose_initializers, _purpose_extraInitializers);
        __esDecorate(null, null, _bedrooms_decorators, { kind: "field", name: "bedrooms", static: false, private: false, access: { has: function (obj) { return "bedrooms" in obj; }, get: function (obj) { return obj.bedrooms; }, set: function (obj, value) { obj.bedrooms = value; } }, metadata: _metadata }, _bedrooms_initializers, _bedrooms_extraInitializers);
        __esDecorate(null, null, _bathrooms_decorators, { kind: "field", name: "bathrooms", static: false, private: false, access: { has: function (obj) { return "bathrooms" in obj; }, get: function (obj) { return obj.bathrooms; }, set: function (obj, value) { obj.bathrooms = value; } }, metadata: _metadata }, _bathrooms_initializers, _bathrooms_extraInitializers);
        __esDecorate(null, null, _category_id_decorators, { kind: "field", name: "category_id", static: false, private: false, access: { has: function (obj) { return "category_id" in obj; }, get: function (obj) { return obj.category_id; }, set: function (obj, value) { obj.category_id = value; } }, metadata: _metadata }, _category_id_initializers, _category_id_extraInitializers);
        __esDecorate(null, null, _subcategory_id_decorators, { kind: "field", name: "subcategory_id", static: false, private: false, access: { has: function (obj) { return "subcategory_id" in obj; }, get: function (obj) { return obj.subcategory_id; }, set: function (obj, value) { obj.subcategory_id = value; } }, metadata: _metadata }, _subcategory_id_initializers, _subcategory_id_extraInitializers);
        __esDecorate(null, null, _country_decorators, { kind: "field", name: "country", static: false, private: false, access: { has: function (obj) { return "country" in obj; }, get: function (obj) { return obj.country; }, set: function (obj, value) { obj.country = value; } }, metadata: _metadata }, _country_initializers, _country_extraInitializers);
        __esDecorate(null, null, _state_decorators, { kind: "field", name: "state", static: false, private: false, access: { has: function (obj) { return "state" in obj; }, get: function (obj) { return obj.state; }, set: function (obj, value) { obj.state = value; } }, metadata: _metadata }, _state_initializers, _state_extraInitializers);
        __esDecorate(null, null, _city_decorators, { kind: "field", name: "city", static: false, private: false, access: { has: function (obj) { return "city" in obj; }, get: function (obj) { return obj.city; }, set: function (obj, value) { obj.city = value; } }, metadata: _metadata }, _city_initializers, _city_extraInitializers);
        __esDecorate(null, null, _district_decorators, { kind: "field", name: "district", static: false, private: false, access: { has: function (obj) { return "district" in obj; }, get: function (obj) { return obj.district; }, set: function (obj, value) { obj.district = value; } }, metadata: _metadata }, _district_initializers, _district_extraInitializers);
        __esDecorate(null, null, _latitude_decorators, { kind: "field", name: "latitude", static: false, private: false, access: { has: function (obj) { return "latitude" in obj; }, get: function (obj) { return obj.latitude; }, set: function (obj, value) { obj.latitude = value; } }, metadata: _metadata }, _latitude_initializers, _latitude_extraInitializers);
        __esDecorate(null, null, _longitude_decorators, { kind: "field", name: "longitude", static: false, private: false, access: { has: function (obj) { return "longitude" in obj; }, get: function (obj) { return obj.longitude; }, set: function (obj, value) { obj.longitude = value; } }, metadata: _metadata }, _longitude_initializers, _longitude_extraInitializers);
        __esDecorate(null, null, _phone_decorators, { kind: "field", name: "phone", static: false, private: false, access: { has: function (obj) { return "phone" in obj; }, get: function (obj) { return obj.phone; }, set: function (obj, value) { obj.phone = value; } }, metadata: _metadata }, _phone_initializers, _phone_extraInitializers);
        __esDecorate(null, null, _user_id_decorators, { kind: "field", name: "user_id", static: false, private: false, access: { has: function (obj) { return "user_id" in obj; }, get: function (obj) { return obj.user_id; }, set: function (obj, value) { obj.user_id = value; } }, metadata: _metadata }, _user_id_initializers, _user_id_extraInitializers);
        __esDecorate(null, null, _status_decorators, { kind: "field", name: "status", static: false, private: false, access: { has: function (obj) { return "status" in obj; }, get: function (obj) { return obj.status; }, set: function (obj, value) { obj.status = value; } }, metadata: _metadata }, _status_initializers, _status_extraInitializers);
        __esDecorate(null, null, _is_trash_decorators, { kind: "field", name: "is_trash", static: false, private: false, access: { has: function (obj) { return "is_trash" in obj; }, get: function (obj) { return obj.is_trash; }, set: function (obj, value) { obj.is_trash = value; } }, metadata: _metadata }, _is_trash_initializers, _is_trash_extraInitializers);
        __esDecorate(null, null, _priority_decorators, { kind: "field", name: "priority", static: false, private: false, access: { has: function (obj) { return "priority" in obj; }, get: function (obj) { return obj.priority; }, set: function (obj, value) { obj.priority = value; } }, metadata: _metadata }, _priority_initializers, _priority_extraInitializers);
        __esDecorate(null, null, _created_at_decorators, { kind: "field", name: "created_at", static: false, private: false, access: { has: function (obj) { return "created_at" in obj; }, get: function (obj) { return obj.created_at; }, set: function (obj, value) { obj.created_at = value; } }, metadata: _metadata }, _created_at_initializers, _created_at_extraInitializers);
        __esDecorate(null, null, _updated_at_decorators, { kind: "field", name: "updated_at", static: false, private: false, access: { has: function (obj) { return "updated_at" in obj; }, get: function (obj) { return obj.updated_at; }, set: function (obj, value) { obj.updated_at = value; } }, metadata: _metadata }, _updated_at_initializers, _updated_at_extraInitializers);
        __esDecorate(null, null, _category_decorators, { kind: "field", name: "category", static: false, private: false, access: { has: function (obj) { return "category" in obj; }, get: function (obj) { return obj.category; }, set: function (obj, value) { obj.category = value; } }, metadata: _metadata }, _category_initializers, _category_extraInitializers);
        __esDecorate(null, null, _community_decorators, { kind: "field", name: "community", static: false, private: false, access: { has: function (obj) { return "community" in obj; }, get: function (obj) { return obj.community; }, set: function (obj, value) { obj.community = value; } }, metadata: _metadata }, _community_initializers, _community_extraInitializers);
        __esDecorate(null, _classDescriptor = { value: _classThis }, _classDecorators, { kind: "class", name: _classThis.name, metadata: _metadata }, null, _classExtraInitializers);
        Property = _classThis = _classDescriptor.value;
        if (_metadata) Object.defineProperty(_classThis, Symbol.metadata, { enumerable: true, configurable: true, writable: true, value: _metadata });
        __runInitializers(_classThis, _classExtraInitializers);
    })();
    return Property = _classThis;
}();
exports.Property = Property;
